### ISSUE TITLE
Wrong return type in AtRules.php

### ISSUE THREAD

**Issue by RobertCordes** [typesetsh/laravel-wrapper#3]
I was trying to use the package on PHP 8.0 and got the following error message:

**Deprecated**: Return type of Typesetsh\Css\Grammar\AtRules::offsetSet($name, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in …/**css/src/Grammar/AtRules.php** on line **72**

**Deprecated**: Return type of Typesetsh\Css\Grammar\AtRules::offsetUnset($name) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in …/**css/src/Grammar/AtRules.php** on line **80**

**Comment by jsiefer** [comment]
Thanks, will be fixed with the next minor typeset.sh release.

**Comment by RobertCordes** [comment]
Awesome. There were actually some more issues like this one, I’ve stumbled upon 10 or so.

**Comment by jsiefer** [comment]
Okay 0.18.15 solves the offsetUnset() and offsetSet() issues - The offsetGet() : mixed return type will have to wait for release 0.19 where we will drop support for php7.2 and php7.3

**Comment by jsiefer** [comment]
This is fixed on version 0.19
