### ISSUE TITLE
Composer minimise filesize of fonts?

### ISSUE THREAD

**Issue by timmaier** [typesetsh/laravel-wrapper#6]
Hey is there a way to omit the following font files from this library?

Found under
`/vendor/typesetsh/font-noto/fonts/sans/`

`NotoSansCJKsc-Bold.otf`
`NotoSansCJKsc-Regular.otf`
`NotoSansCJKsc-Light.otf`

Together these are equal to ~48MB of size. Which when working with laravel vapors 50MB application upload limit does not bode well.

**Comment by jsiefer** [comment]
right,... do you have any option of simply deleting them before deployment as a quick fix?
I'll see if there is something we can do.

**Comment by timmaier** [comment]
Sweet thankyou. 

Yes simply deleting them before deploy locally works for now. If we start getting these problems in CI/CD we'll have to do that there too.

**Comment by jsiefer** [comment]
We have refactored out those files into an additional package with the next up coming release. This should then allow to create a simple composer replace-package that will remove them or allow to register a custom path where those files can be found. Ill keep you posted on this.

**Comment by jsiefer** [comment]
Hi @timmaier - this package should do the trick for you.

https://github.com/typesetsh/font-noto-cjk-sub

**Comment by timmaier** [comment]
Thank you this works perfectly!
